---
apiVersion: v1
kind: ConfigMap
metadata:
  name: welcome-configmap
data:
  welcome.html: |
    <html>
      <head>
        <title>Welcome</title>
      </head>
      <body>
        <h1>Welcome to my website!</h1>
        <p>This is a sample welcome page.</p>
      </body>
    </html>
---