---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome
spec:
  selector:
    matchLabels:
      app: welcome
  replicas: 1
  template:
    metadata:
      labels:
        app: welcome
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---