---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: welcome-service-ingress
  annotations:
    networking.kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: welcome.local.gd
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: welcome-service
            port:
              number: 80
---
